### PR TITLE
Update package dependecies, switch to `pdfjs-dist`

### PR DESCRIPTION
**Pull request by ashthespy**
#### Package maintenance
We had a few ancient and unused packages, not a major issue, but gave it a bump while I was at it :-)

#### Use `pdfjs-dist` instead of bundling it with the package
Should hopefully help with #115 
Taken directly from LaTeX-Workshop implementation. 😉 
I saw some more ideas for the viewer title that I will soon incorporate in here. 
 
Anyone interested to give it a spin before merging?
@exploide ?

### CODE REVIEW

**Comment by exploide** [comment]
Checked it out. When building a pdf, the viewer is empty and shows no document. External viewers render the generated pdf perfectly fine.

When opening developer tools and clicking the magnifier icon again, the viewer window contains the following error message. This happens also for a very small pdf containing only one sentence.

```
PDF.js Version 1.9.573 (build: 50bd4a5a)
Nachricht: Source is too large
```

**Comment by ashthespy** [comment]
Quite strange - might I ask how you built the package? I do see that you have the right `PDF.js` version. 
I will do some digging with a VM and a fresh install.

PS: Ich verstehe ein bisschen Deutsch ;-)

**Comment by exploide** [comment]
I moved my production `.atom` config folder elsewhere and did the following to install the package:
```
git clone git@github.com:James-Yu/Atom-LaTeX.git
cd Atom-LaTeX/
git fetch origin pull/117/head:upstream-pull
git checkout upstream-pull
apm i
apm link .
```

Let me know if I can help to debug the issue :)

**Comment by ashthespy** [comment]
So I just tested this out on my Ubuntu (Xenial) VM and faced some trouble initially as well. What I did.

```
git clone git@github.com:ashthesp/Atom-LaTeX.git
cd Atom-LaTeX/
git checkout upstream-pull
apm install
apm link
```
No dice - just a blank window with nothing on the dev console as well.
But I managed to get it working with (back in Atom-LaTeX dir)
```
git checkout upstream-master
apm install
apm link
```
Build the document once just to check - yes, all good.
```
git checkout upstream-pull
apm install
apm link
```
Now everything works! :-)
So no idea but for some reason the modules are not built properly on the first time?

**Comment by exploide** [comment]
Followed your steps. But after installing the `upstream-pull` branch for the second time, it still does not work. Same behavior as described above.

**Comment by ashthespy** [comment]
Hmm - can you try 
```
cd Atom-LaTeX/
rm -rf node_modules
apm install --verbose
```
to see if there is something going amiss with your OS and the node modules? I just got it to work on a completely fresh VM running Ubuntu Xenial, and am running out of ideas! :-s

**Comment by exploide** [comment]
This is the output of `apm install --verbose`: https://pastebin.com/CRaZc4n0

Maybe the unmet webpack dependency is related to the problem?

I use the atom rpm package from their website on a Fedora 26 system.

**Comment by ashthespy** [comment]
Nope, that is just a npm warning, shouldn't really be an issue :-)
After some time now, and got it up and running on a Fedora 26 VM 😁 
```
wget https://github.com/atom/atom/releases/download/v1.20.0/atom.x86_64.rpm 
sudo dnf install atom.x86_64.rpm 
git clone https://github.com/ashthespy/Atom-LaTeX -b upstream-pull
cd Atom-LaTeX
apm install && apm link && atom .
```

**Comment by ashthespy** [comment]
Okay, big issue. It seems to work only on the tab viewer, and not in the viewer window - across all versions.
Rather than going digging into the pdfjs code, I now have shifted to the [latest official version](https://github.com/mozilla/pdf.js/releases) instead of using the [latest nodejs]package(https://www.npmjs.com/package/pdfjs-dist).
Let me push the new changes - tested (Win10, Ubuntu Xenial and Fedora 26) but not going to take any chances, could you try as well?!

**Comment by exploide** [comment]
Works for me :+1: Nice, seems to be ready now.

No problem, glad I can help improving this package.

**Pull request merged**
