### PR TITLE
Remove pdf page borders  by default

### PR DESCRIPTION
**Pull request by ashthespy**
Quick and dirty fix for https://github.com/James-Yu/Atom-LaTeX/issues/25

### CODE REVIEW

**Comment by James-Yu** [comment]
Actually this is a quick and neat fix. However, I am not very sure on whether the border shadow should be permanently removed. Any suggestions?

**Comment by ashthespy** [comment]
Given the our particular case I don't see why not, the default tab view in in Atom has some padding anyway, so the page border is in fact an additional border. 
Either way, all menus and toolbars (e.g Bookmarks) still respect this minimal border.
 
To be truly flexible, you can add an additional `collapse` button on the toolbar to remove the page borders at some later stage.

**Comment by James-Yu** [comment]
One more thing, please check if reverse synctex can still give the correct result. IIRC the code included some hard-coded coordinate conversions.

**Comment by ashthespy** [comment]
I did some rudimentary checks already on my simple two page document with tables and TikZ files as separate inputs - seems to work quite fine (Both reverse and normal syntex) for me.

**Comment by James-Yu** [comment]
Thanks - I will do some in depth test tmr. It's pretty late now in my place. :D

**Pull request merged**
