### PR TITLE
Update 673affc6b86636051fb73a9f1ad3050ef82714ab  to fix #31

### LINKED ISSUE #31: Handling multiple projects
More of an enhancement than an issue - It's to do with working with multiple documents in parallel.
 
My typical folder/project structure looks something like below:
```
.
└── Document_1
    ├── Img
    ├── .latexcfg
    ├── Document_1.tex
    └── Document_1_Chapter1.tex 
└── Document_2
    ├── Img
    ├── .latexcfg
    ├── Document_2.tex
    └── Document_2_Chapter1.tex
```
Say I work on `Document_1.tex` for a while, and then switch to `Document_2.tex`, unless I manually pick the `LaTeX Root` via the `Set LaTeX Root` icon in the toolbar, the `.latexcfg` in the `Document_2` folder is ignored. So naturally, all configurations still points to `Document_1`, and does not update to the `.latexcfg` in the `Document_2` folder.

One method of overcoming this would be to when reading the `.latexcfg` to add an extra key of `rootdir` and counter check if the `rootdir` of the current editor file and the `.latexcfg` match in [`findMainSequence()`](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/manager.coffee#L48).
What do you think?

### PR DESCRIPTION
**Pull request by ashthespy**
Use [`relativizePath`](https://atom.io/docs/api/v1.15.0/Project#instance-relativizePath) to get current project path and change order in `findMain` to check `findMainConfig` first

### CODE REVIEW

**Comment by James-Yu** [comment]
Never know this API :p

**Comment by ashthespy** [comment]
Any chance this can be included in the next update? :-) Spent quit some time wondering why my changes to my document were not compiling only to realise that I was not on my dev branch package, but the normal one :-P

**Comment by James-Yu** [comment]
Missed that. Will do shortly.

**Comment by ashthespy** [comment]
On using this for some more time, I realise that due to this commit, on every autocomplete provider trigger i.e every time the user types a  `\` the user will get spammed with: 
```
Set the following file as LaTeX main file.
path/to/blah.tex
Reason: The configuration file setting.
```
This is due to [command](https://github.com/James-Yu/Atom-LaTeX/blob/4cce568ac81f6581537e4c3315029d4590206c18/lib/autocomplete/command.coffee#L26) and [reference](https://github.com/James-Yu/Atom-LaTeX/blob/33af8c6a6c90686acf9835a967cc20e0f1def1e8/lib/autocomplete/reference.coffee#L22) providers trying to find all files by calling `manager.findAll()`.

With this commit, I change the order in `manager.findMainSequence` to read the config file for the multiple project support, but this is the by product :-(

There are two options:
1. Temp patch `findMainSequence` so that there are not so log messages are spammed or
1. Use watchers! ( #41) I have some time this weekend, and I see from the https://github.com/James-Yu/LaTeX-Workshop/pull/71 that you have it up and working so shall try porting the logic over!

What do you think? :-)

**Pull request merged**
