### PR TITLE
Add new '%EXT' placeholder for custom toolchains

### PR DESCRIPTION
**Pull request by ashthespy**
Follow up from #89 and #90 that should provide a solution for #86 and #42

### CODE REVIEW

**Comment by James-Yu** [comment]
Will release soon.

**Comment by ashthespy** [comment]
Can you hold on for a few hours? Will add more small stuff :-)

**Comment by ashthespy** [comment]
Sorry, had a rather busy weekend - but should be all good now!
Would you like me to edit the pull requests and add a line with information for the `Changelog.md` file?

**Comment by James-Yu** [comment]
That would actually be awesome!

**Comment by ashthespy** [comment]
Done, but this might save you more time ;-)


```
### Changed
* [(#50)](https://github.com/James-Yu/Atom-LaTeX/pull/50) Preliminary `arara` log parsing support
* [(#97)](https://github.com/James-Yu/Atom-LaTeX/pull/97) Add new `%EXT` placeholder for custom toolchains
* [(#98)](https://github.com/James-Yu/Atom-LaTeX/pull/98) Add `.bib` to subfile-autocomplete + code clean up
* [(#100)](https://github.com/James-Yu/Atom-LaTeX/pull/100) Add error notification for invalid LaTeX root file
### Fixed
* [(#102)](https://github.com/James-Yu/Atom-LaTeX/pull/102) Fix root directory determination
```

**Pull request merged**
