### PR TITLE
Rewrote and extended the log parser.

### PR DESCRIPTION
**Pull request by sbdfh**
This is a proposed improvement for #159. I think it is still not catching all warnings, but significantly more. A further improvement is a better determination for lastFile in the log. 
The downside is that the parser now does two passes of the log instead of one.

### CODE REVIEW

**Comment by sbdfh** [comment]
I did not touch the whole arara part. Putting an arara log directly through the parser works.
However, when calling arara through atom-latex the build log only shows
>arara --log  [file]
>
>[arara ascii art]
>
>Running PDFLaTeX... SUCCESS

Are you sure that this is a problem with the parser? If so: can you tell me how to get this to work so I can debug it?

**Comment by ashthespy** [comment]
Ah, you need to ask arara to log to the stdio - so  `arara %DOC -v`

**Comment by sbdfh** [comment]
I am seriously confused right now. For me this works with arara and latexmk. 
The parser even finds the newly implemented hyperref warnings (this is a slight change of your MWE):
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{hyperref}

\begin{document}
\title{Minimal document for maximum testing.}
\maketitle

Section \ref{sec:SecA} is defined, but Section \ref{sec:secC} is still WIP.
\section{Section A: $F$igures}
\label{sec:SecA}
\begin{figure}[h]
\centering
 \includegraphics[width=.5\textwidth]{example-image-a}
 \caption{Standart Reification}
 \label{fig:ExampleA}
\end{figure}

\section{Section B: Todo}
\label{sec:SecB}

\end{document}
```
I obtain 
feh_003795_000001_screenshot_1535956718312839732
I suspect this is a problem with my identification of tex files vs. Host OS. Could you provide me the full log for your MWE on your machine?

**Comment by ashthespy** [comment]
aha! The plot thickens! I am on Win10, here is the [raw log](https://pastebin.com/w9uXgWrS)

**Comment by ashthespy** [comment]
Yep, that fixed it! 
Do you feel any other tests are needed or is it ready to merge?

**Comment by sbdfh** [comment]
Ok, there is some seriously evil magic going on here, that I do not understand.
As I suspected, the problem was input file name recognition. I searched for 
`(./`
which is how input files begin in unix latex logs. However, the raw logs you showed me for win, there is no dot and slash (see line 12 in arara and line 8 in latexmk, where it is just 
`(minimal.tex`
). However, this is why is it completely elusive to me the current parser works. Your screencaps proved that it correctly recognizes minimal.tex as the source of the warning. However the RegEx `/^.*?\(\.\/(.*?\.\w+)/` simply does not match the line `(minimal.tex`, so there is something more going on.

That being said, it is kinda difficult to identify input files when allowing full generality. For example, overfull box warnings have
`(9.43824pt too wide`
which might go through as a file name, since it matches `(.*?\.\w+)`. 
I have commited a solution which works as long as the file endings of input files contain no digits. I currently have no better idea how to solve this problem.

**Comment by ashthespy** [comment]
>However, this is why is it completely elusive to me the current parser works. Your screencaps proved that it correctly recognizes minimal.tex as the source of the warning. However the RegEx /^.*?\(\.\/(.*?\.\w+)/ simply does not match the line (minimal.tex, so there is something more going on.

The file level warnings are captured by this parsing the warnings directly, that are generated by passing in the `-file-line-error` flag to the engine. 
```coffee
if result
        items.push
          type: 'error',
          text: if result[3] and result[3] != 'LaTeX' then \
                """#{result[3]}: #{result[4]}""" else result[4],
          file: if result[1] then \
            path.resolve(path.dirname(@latex.mainFile), result[1]) else \
            @latex.mainFile
          line: if result[2] then parseInt result[2], 10 else undefined
```
Hence for an error in `\include{incldues/macros}` the log results in:
```latex
\@input{incldues/macros.aux}
(incldues/macros.tex

incldues/macros.tex:17: LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help
)
```
But maybe an idea is to match the preceding lines for `filename.aux`? I must say though, I am not really well versed in latex log stuff!

**Comment by sbdfh** [comment]
> But maybe an idea is to match the preceding lines for filename.aux?
That is actually the best idea to solve this, I think. This increases the complexity of the parser, however, for all intends and purposes this should be fine. I did a few checks and it did not really affect compile time. I guess this might be noticeable for really huge projects, but then this is most likely dominated by LaTeX's build time anyways.

I am happy with this now and I think it it compatible to all platforms now, as well.

**Comment by ashthespy** [comment]
@sbdfh will check it on windows in a few, might I ask what platform you've tested it on?
Btw - I was looking at how others do this and found [`latex-log-parser-sharelatex`](https://github.com/sharelatex/latex-log-parser-sharelatex) didn't go through it completely though.

**Comment by sbdfh** [comment]
I'm on Linux using the current texlive installation. 
The [latex-log-parser-sharelatex](https://github.com/sharelatex/latex-log-parser-sharelatex) parser is actually quite similar. At some point it might have been the basis for atom-latex? 
Quick inspection tells me, they are also parsing one line at a time, and trying to detect multiline warnings. Which is a decent alternative. However, this seems to sometimes lead warnings attributed to the wrong source file? I might check that out if I have some additional spare time.

**Comment by sbdfh** [comment]
This won't solve the problem I initially started to fix. The current parser does not pick up warnings of packages that include linebreaks. These linebreaks are unaffected by max_print_lines because these are in the warning message.

**Pull request merged**
